import enum
from sqlalchemy import Column, Integer, String, Enum, DateTime, ForeignKey, Text, JSON
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.database.connection import Base


class OrderStatus(str, enum.Enum):
    PENDING_CONFIRMATION = "PENDING_CONFIRMATION"
    CONFIRMED = "CONFIRMED"
    CANCELLED = "CANCELLED"
    UPDATED = "UPDATED"


class Customer(Base):
    """
    Represents a customer in the database.
    Stores basic info mapping to Shopify and long-term memory for AI context.
    """
    __tablename__ = "customers"

    id = Column(Integer, primary_key=True, index=True)
    shopify_customer_id = Column(String, unique=True, index=True, nullable=True)
    name = Column(String, nullable=True)
    email = Column(String, unique=True, index=True, nullable=True)
    phone = Column(String, unique=True, index=True, nullable=True)
    
    # Store persistent AI facts globally about this user
    # e.g., "Prefers fast shipping", "Is a VIP"
    long_term_memory = Column(Text, nullable=True) 

    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    orders = relationship("Order", back_populates="customer")
    conversations = relationship("Conversation", back_populates="customer")


class Order(Base):
    """
    Tracks local state of Shopify orders managed by the AI Agent.
    """
    __tablename__ = "orders"

    id = Column(Integer, primary_key=True, index=True)
    shopify_order_id = Column(String, unique=True, index=True, nullable=False)
    customer_id = Column(Integer, ForeignKey("customers.id"), nullable=False)
    
    status = Column(Enum(OrderStatus), default=OrderStatus.PENDING_CONFIRMATION, nullable=False)
    total_price = Column(String, nullable=True)
    
    # Snapshot of the last known order data from Shopify to minimize API calls
    order_data_snapshot = Column(JSON, nullable=True)

    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    customer = relationship("Customer", back_populates="orders")


class Conversation(Base):
    """
    Represents an ongoing or past interaction thread between Customer and AI.
    """
    __tablename__ = "conversations"

    id = Column(Integer, primary_key=True, index=True)
    customer_id = Column(Integer, ForeignKey("customers.id"), nullable=True)
    
    # Optional explicitly linked order being discussed
    linked_order_id = Column(Integer, ForeignKey("orders.id"), nullable=True)
    
    # Keep track of the actual dialog history
    history = Column(JSON, default=list, nullable=False)
    
    # Short summary of the conversation generated by the AI upon completion
    summary = Column(Text, nullable=True)

    # WebSocket/chat session key — used to restore in-memory SessionMemory after restart
    session_key = Column(String, unique=True, index=True, nullable=True)

    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    customer = relationship("Customer", back_populates="conversations")
